---
title: "Analysis"
author: "Filip Dechterenko"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: html_document
---

# Load libraries

```{r libraries and preparation}
set.seed(190425)
library(tidyverse); theme_set(theme_classic(16))
library(lme4)
library(here)

source(here("R","utils.R"))
```

# Load data

Data were preprocesseb by scripts 

```{r load data, warning=FALSE, message=FALSE}

df <- readRDS(here("data", "exp_DRM1", "results_191017.rds"))

df_participants <- readxl::read_excel(here::here("data","exp_DRM1","participants_190509.xlsx"))

plots_dir <- here("plots", "exp_DRM1")

if(!dir.exists(plots_dir)) { dir.create(plots_dir) }

df <- df %>% left_join(df_participants, by = c("subject_id"))

df2 <- readRDS(here("data/exp_DRM1/results_with_tgtdistances_fc7_200219.rds"))
df2_conv5 <- readRDS(here("data/exp_DRM1/results_with_tgtdistances_conv5_200219.rds"))
```

# Duration of the exp

```{r duration of the exp}
data_pth <- here("data", "exp_DRM1", "results") 

exp_duration <- data_pth %>% 
  dir(pattern = "*.log", full.names = T) %>% 
  purrr::map(read_file) %>% 
  purrr::map_dbl(get_dur) 


```
Average experiment duration: `r (exp_duration / 60) %>% mean() %>% round(2)`, SD = `r (exp_duration / 60) %>% sd() %>% round(2)`

# Desc stat



## Participant data

```{r participant desc}
df_participants %>% summarize(n_total = n(), m_age = mean(age), sd_age = sd(age), n_males = sum(gender == "M"), n_payments = sum(payment == "yes")) %>% knitr::kable(digits=2)
```



```{r desc stat}
df %>% group_by(subject_id, type) %>% 
  summarize(correct = mean(correct)) %>% 
  group_by(type) %>% 
  summarize(m = mean(correct), sd = sd(correct)) %>% 
  knitr::kable(digits = 2)

df %>% group_by(subject_id, type) %>% 
  filter(type != "target") %>% 
  summarize(correct = 1-mean(correct)) %>% 
  group_by(type) %>% 
  summarize(m = mean(correct), sd = sd(correct)) %>% 
  knitr::kable(digits = 2)
```



## And visualize

```{r results accuracy}

p <- df %>%
  group_by(subject_id, type) %>% 
  summarize(correct = mean(correct)) %>% 
  ggplot(aes(x = type, y = correct)) + 
  ylim(0,1)+
  theme(aspect.ratio = 1) +
  geom_hline(yintercept = .5) +
  ylab("Percentage correct") +
  geom_violin(trim = F)+
  stat_summary(fun.data = "mean_cl_boot") + 
  xlab("Type") +
  theme(text = element_text(size = 24))
  
p
ggsave(file.path(plots_dir, "Figure8.svg"), p, width = 6, height = 6)

```


# Dprime analysis

```{r two dprimes and bias}
df_dprime2 <- df %>% 
  group_by(subject_id) %>% 
  summarize(H = sum(key_resp == "old" & corrKey == "old")/(sum(corrKey == "old")),
            FA_close = sum(key_resp == "old" & corrKey == "new" & type == "close distractor")/(sum(corrKey == "new" & type == "close distractor")),
            FA_far = sum(key_resp == "old" & corrKey == "new" & type == "far distractor")/(sum(corrKey == "new" & type == "far distractor"))) %>% 
  mutate(d_oldclose = qnorm(H) - qnorm(FA_close),
         d_oldfar = qnorm(H) - qnorm(FA_far),
         c_oldclose = -0.5*(qnorm(H) + qnorm(FA_close)),
         c_oldfar = -0.5*(qnorm(H) + qnorm(FA_far)))
t.test(df_dprime2$d_oldclose, df_dprime2$d_oldfar, paired = T)
t.test(df_dprime2$c_oldclose, df_dprime2$c_oldfar, paired = T)  
colMeans(df_dprime2)

df_dprime2

mean(df_dprime2$d_oldclose) %>% round(2)
mean(df_dprime2$d_oldfar) %>% round(2)
sd(df_dprime2$d_oldclose) %>% round(2)
sd(df_dprime2$d_oldfar) %>% round(2)

mean(df_dprime2$c_oldclose) %>% round(2)
mean(df_dprime2$c_oldfar) %>% round(2)
sd(df_dprime2$c_oldclose) %>% round(2)
sd(df_dprime2$c_oldfar) %>% round(2)
```

```{r use rating to compute ROC}

df_oldclose <- create_roc_data(df, without_type = "far distractor")

df_oldfar <- create_roc_data(df, without_type = "close distractor")

df_oldclose_agg <- df_oldclose %>% group_by(var) %>% summarize(Hs = mean(Hs), FAs = mean(FAs), dprime = mean(dprime))

df_oldfar_agg <- df_oldfar %>% group_by(var) %>% summarize(Hs = mean(Hs), FAs = mean(FAs), dprime = mean(dprime))


p1 <- df_oldclose %>% ggplot(aes(x = FAs, y = Hs, group = as.factor(subject_id))) + 
  geom_path(alpha = I(0.2)) + 
  xlim(0,1) + 
  ylim(0,1) + 
  geom_segment(x = 0, y = 0, xend = 1,yend = 1) +
  theme(aspect.ratio = 1) +
  geom_path(data = df_oldclose_agg, group = 1, size = 1.5, col = "red") + 
  ggtitle("Target - Close distractor") +
  theme(text = element_text(size = 24))

p2 <- df_oldfar %>% ggplot(aes(x = FAs, y = Hs, group = as.factor(subject_id))) + 
  geom_path(alpha = I(0.2)) + 
  xlim(0,1) + 
  ylim(0,1) + 
  geom_segment(x = 0, y = 0, xend = 1,yend = 1) +
  theme(aspect.ratio = 1) +
  geom_path(data = df_oldfar_agg, group = 1, size = 1.5, col = "red") + 
  ggtitle("Target - Far distractor") +
  theme(text = element_text(size = 24))

ggsave(file.path(plots_dir, "Figure9_left.svg"), p1, width = 6, height = 6)

ggsave(file.path(plots_dir, "Figure_right.svg"), p2, width = 6, height = 6)

```

```{r slopes ROC}
slope_oldclose <- get_ROC_slopes(df_oldclose)
slope_oldfar <- get_ROC_slopes(df_oldfar)
intercepts_oldclose <- get_ROC_intercepts(df_oldclose)
intercepts_oldfar   <- get_ROC_intercepts(df_oldfar)


df_dprime2_da <- df_dprime2 %>% mutate(s_oldclose = slope_oldclose,
                      s_oldfar = slope_oldfar) %>% 
  mutate(da_oldclose = compute_da(H,FA_close,s_oldclose),
         da_oldfar = compute_da(H,FA_far,s_oldfar))



mean(df_dprime2_da$da_oldclose) %>% round(2)
mean(df_dprime2_da$da_oldfar) %>% round(2)
sd(df_dprime2_da$da_oldclose) %>% round(2)
sd(df_dprime2_da$da_oldfar) %>% round(2)


df_dprime2_da %>% select(da_oldclose,da_oldfar) %>% arrange(da_oldfar)
t.test(df_dprime2_da$da_oldclose, df_dprime2_da$da_oldfar, paired = T) %>% apa::apa()
lsr::cohensD(df_dprime2_da$da_oldclose, df_dprime2_da$da_oldfar,method = "paired") %>% round(2)
```

slope
*  old-close: `r mean(slope_oldclose) %>% round(2)`, SD = `r sd(slope_oldclose) %>% round(2)`
*  old-far: `r mean(slope_oldfar) %>% round(2)`, SD = `r sd(slope_oldfar) %>% round(2)`

```{r test nonunit slope}

t.test(slope_oldclose, mu = 1)
t.test(slope_oldfar, mu = 1)
```

```{r SDT model plot}
df_dprime <- df %>% group_by(subject_id,type) %>% 
  
  summarize(yes = mean(key_resp == "old"),
            zH = qnorm(yes)) %>% 
  mutate(d_old_close = zH[type == "target"]-zH[type == "close distractor"],
         d_old_far = zH[type == "target"]-zH[type == "far distractor"],
         d_close_far = zH[type == "close distractor"]-zH[type == "far distractor"])


df_dprime_agg <- df_dprime %>% 
  group_by(type) %>% 
  summarize(m = mean(zH),sd = sd(zH))

df_dprime_agg

x0 <- (-400:400)/100

y_close  <- dnorm(x0, df_dprime_agg$m[df_dprime_agg$type == "close distractor"], mean(slope_oldclose))
y_far  <- dnorm(x0, df_dprime_agg$m[df_dprime_agg$type == "far distractor"], mean(slope_oldfar))
y_target  <- dnorm(x0, df_dprime_agg$m[df_dprime_agg$type == "target"], 1)

df_plot <- tibble(x = rep(x0,3), y = c(y_close, y_far, y_target), type = rep(c("close distractor","far distractor","target"), each = length(x0)))

p_SDT_model <- df_plot %>% ggplot(aes(x = x, y = y, col = type)) + geom_path(size = 1.2) + geom_vline(xintercept = 0) +
  theme(aspect.ratio = 1)
p_SDT_model
ggsave(file.path(plots_dir, "Figure10.svg"), p_SDT_model, width = 6, height = 6)

(df_dprime_agg$m[df_dprime_agg$type == "close distractor"]-df_dprime_agg$m[df_dprime_agg$type == "target"]) %>% round(2)

(df_dprime_agg$m[df_dprime_agg$type == "far distractor"]-df_dprime_agg$m[df_dprime_agg$type == "close distractor"]) %>% round(2)
```

## Test 

```{r overall glmer}
lm1 <- glmer(correct~type+(1+type|subject_id) + (1|category), df %>% filter(type!="target"), family = binomial())

lmnull <- glmer(correct~1+(1+type|subject_id) + (1|category), df %>% filter(type!="target"), family = binomial())

anova(lm1,lmnull)
```

```{r one sample tests}
df_for_onettest <- df %>% group_by(subject_id,type) %>% summarize(correct = mean(correct))
df_for_onettest %>% group_by(type) %>% do(t.test(.$correct, mu = .5) %>% broom::tidy()) %>% 
  left_join(df_for_onettest %>% group_by(type) %>% do(d=lsr::cohensD(.$correct, mu = .5)) %>% mutate(d = unlist(d)),
            by = "type")


```
